// Skills by category. Mirrors docs/skills/*.md.
import {
  Atom,
  Cloud,
  Database,
  Cpu,
  Sparkles,
  Smartphone,
  Wrench,
} from "lucide-react";

export type Category = {
  id: string;
  label: string;
  color: string;
  icon: typeof Atom;
  skills: { name: string; level: number }[];
};

export const categories: Category[] = [
  {
    id: "frontend",
    label: "Frontend",
    color: "#22D3EE",
    icon: Atom,
    skills: [
      { name: "React", level: 96 },
      { name: "Next.js", level: 94 },
      { name: "TypeScript", level: 93 },
      { name: "Tailwind CSS", level: 95 },
      { name: "Redux Toolkit", level: 90 },
      { name: "TanStack Query", level: 86 },
      { name: "JavaScript", level: 95 },
      { name: "Context API", level: 90 },
      { name: "React Router", level: 90 },
      { name: "Material UI", level: 85 },
      { name: "Shadcn UI", level: 88 },
      { name: "HTML5", level: 96 },
      { name: "CSS3", level: 94 },
      { name: "Responsive Design", level: 95 },
      { name: "Accessibility", level: 88 },
      { name: "Performance", level: 88 },
    ],
  },
  {
    id: "backend",
    label: "Backend",
    color: "#00D4FF",
    icon: Cpu,
    skills: [
      { name: "Node.js", level: 94 },
      { name: "Express.js", level: 93 },
      { name: "REST APIs", level: 94 },
      { name: "GraphQL", level: 88 },
      { name: "Microservices", level: 86 },
      { name: "Socket.IO", level: 88 },
      { name: "JWT", level: 90 },
      { name: "OAuth", level: 88 },
      { name: "Auth & RBAC", level: 88 },
      { name: "BullMQ", level: 84 },
      { name: "RabbitMQ", level: 84 },
      { name: "Webhooks", level: 84 },
      { name: "Cron Jobs", level: 85 },
      { name: "Payments", level: 80 },
      { name: "File Processing", level: 85 },
      { name: "Distributed Systems", level: 84 },
    ],
  },
  {
    id: "data",
    label: "Databases",
    color: "#10B981",
    icon: Database,
    skills: [
      { name: "MongoDB", level: 92 },
      { name: "Mongoose", level: 90 },
      { name: "PostgreSQL", level: 88 },
      { name: "Prisma", level: 86 },
      { name: "Redis", level: 84 },
      { name: "Firebase", level: 86 },
      { name: "Supabase", level: 82 },
      { name: "Cloudinary", level: 86 },
      { name: "MinIO", level: 80 },
    ],
  },
  {
    id: "devops",
    label: "DevOps",
    color: "#8B5CF6",
    icon: Cloud,
    skills: [
      { name: "Docker", level: 92 },
      { name: "Docker Compose", level: 90 },
      { name: "GitHub Actions", level: 88 },
      { name: "CI/CD", level: 88 },
      { name: "Nginx", level: 82 },
      { name: "AWS EC2", level: 85 },
      { name: "AWS S3", level: 86 },
      { name: "AWS RDS", level: 82 },
      { name: "AWS ECS", level: 80 },
      { name: "AWS ECR", level: 80 },
      { name: "Prometheus", level: 80 },
      { name: "Grafana", level: 82 },
      { name: "Linux", level: 86 },
      { name: "Monitoring", level: 84 },
      { name: "Logging", level: 84 },
    ],
  },
  {
    id: "ai",
    label: "AI Engineering",
    color: "#EC4899",
    icon: Sparkles,
    skills: [
      { name: "MCP", level: 92 },
      { name: "Claude Code", level: 92 },
      { name: "Cursor", level: 90 },
      { name: "AI-Assisted Dev", level: 90 },
      { name: "LLM Integration", level: 88 },
      { name: "Prompt Engineering", level: 88 },
      { name: "AI Workflows", level: 86 },
      { name: "Developer Tooling", level: 88 },
    ],
  },
  {
    id: "mobile",
    label: "Mobile",
    color: "#F59E0B",
    icon: Smartphone,
    skills: [
      { name: "React Native", level: 88 },
      { name: "Expo", level: 86 },
      { name: "React Navigation", level: 86 },
      { name: "Push Notifications", level: 84 },
      { name: "Cross-Platform", level: 86 },
    ],
  },
  {
    id: "tools",
    label: "Tools",
    color: "#22D3EE",
    icon: Wrench,
    skills: [
      { name: "Git", level: 94 },
      { name: "GitHub", level: 94 },
      { name: "VS Code", level: 92 },
      { name: "Cursor", level: 90 },
      { name: "Postman", level: 90 },
      { name: "Vercel", level: 88 },
      { name: "Netlify", level: 88 },
      { name: "Figma", level: 80 },
    ],
  },
];
